name: Continuous deployment

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: ['v*']

jobs:
  release:
    needs: build
    name: Create release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create a Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
