name: Continuous integration

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install ESLint and dependencies
        run: npm ci
        working-directory: ./hexionbunker/rootfs/opt/hexionbunker
      - name: Run ESLint
        run: node_modules/eslint/bin/eslint.js app.js
        working-directory: ./hexionbunker/rootfs/opt/hexionbunker

  test:
    needs: lint
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test docker build
        run: docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/data homeassistant/amd64-builder --target hexionbunker --amd64 --test

  build:
    needs: test
    name: Build image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/data homeassistant/amd64-builder --target hexionbunker --all --docker-user ${{ secrets.DOCKER_USERNAME }} --docker-password ${{ secrets.DOCKER_PASSWORD }}
