name: CI

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install ESLint and dependencies
        run: npm ci
        working-directory: ./hexionbunker/rootfs/opt/hexionbunker
      - name: Run ESLint
        run: node_modules/eslint/bin/eslint.js app.js
        working-directory: ./hexionbunker/rootfs/opt/hexionbunker

  docker:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test docker build
        run: docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/data homeassistant/amd64-builder --target hexionbunker --amd64 --test
      - name: Build and push Docker image
        run: docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd)":/data homeassistant/amd64-builder --target hexionbunker --all --docker-user ${{ secrets.DOCKER_USERNAME }} --docker-password ${{ secrets.DOCKER_PASSWORD }}
